[from-sip]
exten => 8028,1,NoOp(Voice-to-Voice Farmer Advisor SIP call)
 same => n,Answer()
 same => n,Set(AUDIO_SOCKET_ID=${RAND(10000000,99999999)}-${RAND(1000,9999)}-${RAND(1000,9999)}-${RAND(1000,9999)}-${RAND(1000,9999)}${RAND(1000,9999)}${RAND(1000,9999)})
 same => n,AudioSocket(${AUDIO_SOCKET_ID},phone-gateway:9092)
 same => n,Hangup()

exten => _X.,1,Playback(invalid)
 same => n,Hangup()
