[general]
enabled = yes
webenabled = no
port = 5038
bindaddr = 0.0.0.0

[farmer_admin]
secret = farmer_admin_dev
read = system,call,log,verbose,command,agent,user,originate
write = system,call,log,verbose,command,agent,user,originate
